# Generated by Django 3.0.5 on 2020-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_status_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'projet'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'statut'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tâche'},
        ),
    ]
