# Generated by Django 3.0.5 on 2020-05-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_auto_20200504_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
            preserve_default=False,
        ),
    ]
